from __future__ import annotations

from collections import OrderedDict
from collections.abc import Iterable


def _bone_map(names: Iterable[str]) -> OrderedDict[str, str]:
    return OrderedDict((f'bone_{index}', name) for index, name in enumerate(names))


# to add others, maybe?
NAMING_SCHEMES = OrderedDict([
    ('lara', _bone_map((
        'root', 'hip', 'spine_1', 'spine_2', 'neck', 'head',
        'jaw', 'tongue_1', 'tongue_2', 'lip_lower_c', 'lip_lower_r', 'lip_lower_l',
        'eyelid_lower_l', 'eyebrow_3_l', 'eyebrow_2_l', 'eyebrow_1_l', 'eyebrow_1_r', 'eyebrow_2_r',
        'eyebrow_3_r', 'eye_l', 'eyelid_upper_l', 'eye_r', 'eyelid_upper_r', 'eyelid_lower_r',
        'nose', 'lip_upper_r', 'lip_corner_r', 'lip_upper_c', 'lip_upper_c_2', 'lip_upper_l',
        'lip_corner_l', 'hair_1', 'hair_2', 'hair_3', 'hair_4', 'hair_5',
        'hair_6', 'hair_7', 'hair_8', 'hair_9', 'hair_10', 'cheek_l',
        'cheek_r', 'hair_fix_1', 'hair_fix_2', 'hair_fix_3', 'hair_fix_4', 'hair_fix_5',
        'hair_fix_6', 'hair_fix_7', 'hair_fix_8', 'hair_fix_9', 'hair_fix_10', 'hair_fringe',
        'breast_l', 'breast_end_l', 'breast_r', 'breast_end_r', 'shoulder_l', 'bicep_l',
        'elbow_l', 'wrist_l', 'index1_l', 'index2_l', 'index3_l', 'middle1_l',
        'middle2_l', 'middle3_l', 'ring1_l', 'ring2_l', 'ring3_l', 'pinky1_l',
        'pinky2_l', 'pinky3_l', 'thumb1_l', 'thumb2_l', 'weapon_l', 'wrist_fix_l',
        'bicep_fix_l', 'shoulder_r', 'bicep_r', 'elbow_r', 'wrist_r', 'index1_r',
        'index2_r', 'index3_r', 'middle1_r', 'middle2_r', 'middle3_r', 'ring1_r',
        'ring2_r', 'ring3_r', 'pinky1_r', 'pinky2_r', 'pinky3_r', 'thumb1_r',
        'thumb2_r', 'weapon_r', 'wrist_fix_r', 'bicep_fix_r', 'pelvis', 'thigh_l',
        'calf_l', 'ankle_l', 'toe_l', 'thigh_r', 'calf_r', 'ankle_r',
        'toe_r',
    ))),
    ('larson/pierre', _bone_map((
        'root', 'hip', 'spine_1', 'spine_2', 'neck', 'head',
        'jaw', 'lip_lower_c', 'lip_lower_r', 'lip_lower_l', 'eye_l', 'nose',
        'lip_upper_c', 'lip_upper_l', 'lip_corner_l', 'cheek_l', 'eyelid_lower_l', 'eyelid_upper_l',
        'eyebrow_1_l', 'eyebrow_2_l', 'eyebrow_3_l', 'lip_corner_r', 'lip_upper_r', 'cheek_r',
        'eyelid_lower_r', 'eyebrow_1_r', 'eyebrow_2_r', 'eyebrow_3_r', 'eyelid_upper_r', 'eye_r',
        'shoulder_l', 'bicep_l', 'elbow_l', 'wrist_l', 'ring1_l', 'ring2_l',
        'ring3_l', 'index1_l', 'index2_l', 'index3_l', 'middle1_l', 'middle2_l',
        'middle3_l', 'thumb1_l', 'thumb2_l', 'pinky1_l', 'pinky2_l', 'pinky3_l',
        'shoulder_r', 'bicep_r', 'elbow_r', 'wrist_r', 'ring1_r', 'ring2_r',
        'ring3_r', 'index1_r', 'index2_r', 'index3_r', 'middle1_r', 'middle2_r',
        'middle3_r', 'thumb1_r', 'thumb2_r', 'pinky1_r', 'pinky2_r', 'pinky3_r',
        'pelvis', 'thigh_l', 'calf_l', 'ankle_l', 'toe_l', 'thigh_r',
        'calf_r', 'ankle_r', 'toe_r',
    ))),
    ('natla', _bone_map((
        'root', 'hip', 'spine_1', 'spine_2', 'breast_r', 'breast_end_r',
        'breast_l', 'breast_end_l', 'neck', 'head', 'jaw', 'tongue_1',
        'tongue_2', 'lip_lower_c', 'lip_lower_r', 'lip_lower_l', 'eyelid_lower_l', 'eyebrow_3_l',
        'eyebrow_2_l', 'eyebrow_1_l', 'eyebrow_1_r', 'eyebrow_2_r', 'eyebrow_3_r', 'eye_l',
        'eyelid_upper_l', 'eye_r', 'eyelid_upper_r', 'eyelid_lower_r', 'nose', 'lip_upper_r',
        'lip_corner_r', 'lip_upper_c', 'lip_upper_l', 'lip_corner_l', 'cheek_l', 'cheek_r',
        'hair_fringe', 'hair1_r', 'hair2_r', 'hair3_r', 'hair4_r', 'hair5_r',
        'hair6_r', 'hair7_r', 'hair8_r', 'hair1_c', 'hair2_c', 'hair3_c',
        'hair4_c', 'hair5_c', 'hair6_c', 'hair7_c', 'hair8_c', 'hair1_c',
        'hair2_l', 'hair3_l', 'hair4_l', 'hair5_l', 'hair6_l', 'hair7_l',
        'hair8_l', 'scarf_tie', 'shoulder_l', 'bicep_l', 'elbow_l', 'wrist_l',
        'index1_l', 'index2_l', 'index3_l', 'middle1_l', 'middle2_l', 'middle3_l',
        'ring1_l', 'ring2_l', 'ring3_l', 'pinky1_l', 'pinky2_l', 'pinky3_l',
        'thumb1_l', 'thumb2_l', 'weapon_l', 'shoulder_r', 'bicep_r', 'elbow_r',
        'wrist_r', 'index1_r', 'index2_r', 'index3_r', 'middle1_r', 'middle2_r',
        'middle3_r', 'ring1_r', 'ring2_r', 'ring3_r', 'pinky1_r', 'pinky2_r',
        'pinky3_r', 'thumb1_r', 'thumb2_r', 'weapon_r', 'pelvis', 'thigh_l',
        'calf_l', 'ankle_l', 'toe_l', 'thigh_r', 'calf_r', 'ankle_r',
        'toe_r',
    ))),
    ('kid', _bone_map((
        'root', 'hip', 'spine_1', 'spine_2', 'neck', 'head',
        'jaw', 'lip_lower_l', 'lip_lower_c', 'lip_lower_r', 'eye_l', 'eye_r',
        'eyelid_upper_l', 'eyelid_upper_r', 'eyebrow_1_l', 'eyebrow_2_l', 'eyebrow_3_l', 'eyebrow_1_r',
        'eyebrow_2_r', 'eyebrow_3_r', 'eyelid_lower_l', 'eyelid_lower_r', 'cheek_l', 'cheek_r',
        'nose', 'lip_corner_l', 'lip_corner_r', 'lip_upper_l', 'lip_upper_c', 'lip_upper_r',
        'earring_l', 'earring_r', 'chain_chest', 'shoulder_l', 'bicep_l', 'elbow_l',
        'wrist_l', 'ring1_l', 'ring2_l', 'ring3_l', 'index1_l', 'index2_l',
        'index3_l', 'middle1_l', 'middle2_l', 'middle3_l', 'pinky1_l', 'pinky2_l',
        'pinky3_l', 'thumb1_l', 'thumb2_l', 'shoulder_r', 'bicep_r', 'elbow_r',
        'wrist_r', 'ring1_r', 'ring2_r', 'ring3_r', 'index1_r', 'index2_r',
        'index3_r', 'middle1_r', 'middle2_r', 'middle3_r', 'pinky1_r', 'pinky2_r',
        'pinky3_r', 'thumb1_r', 'thumb2_r', 'pelvis', 'chain_front_1', 'chain_front_2',
        'chain_back_1', 'chain_back_2', 'thigh_l', 'calf_l', 'ankle_l', 'toe_l',
        'thigh_r', 'calf_r', 'ankle_r', 'toe_r',
    ))),
    ('kold', _bone_map((
        'root', 'hip', 'spine_1', 'spine_2', 'neck', 'head',
        'jaw', 'lip_lower_l', 'lip_lower_c', 'lip_lower_r', 'eye_l', 'eye_r',
        'eyelid_upper_l', 'eyelid_upper_r', 'eyebrow_1_l', 'eyebrow_2_l', 'eyebrow_3_l', 'eyebrow_1_r',
        'eyebrow_2_r', 'eyebrow_3_r', 'eyelid_lower_l', 'eyelid_lower_r', 'cheek_l', 'cheek_r',
        'nose', 'lip_corner_l', 'lip_corner_r', 'lip_upper_l', 'lip_upper_c', 'lip_upper_r',
        'shoulder_l', 'bicep_l', 'elbow_l', 'wrist_l', 'ring1_l', 'ring2_l',
        'ring3_l', 'index1_l', 'index2_l', 'index3_l', 'middle1_l', 'middle2_l',
        'middle3_l', 'pinky1_l', 'pinky2_l', 'pinky3_l', 'thumb1_l', 'thumb2_l',
        'shoulder_r', 'bicep_r', 'elbow_r', 'wrist_r', 'ring1_r', 'ring2_r',
        'ring3_r', 'index1_r', 'index2_r', 'index3_r', 'middle1_r', 'middle2_r',
        'middle3_r', 'pinky1_r', 'pinky2_r', 'pinky3_r', 'thumb1_r', 'thumb2_r',
        'jacket_1_1', 'jacket_1_2', 'jacket_1_3', 'jacket_1_4', 'jacket_1_5', 'jacket_2_1',
        'jacket_2_2', 'jacket_2_3', 'jacket_2_4', 'jacket_2_5', 'jacket_3_1', 'jacket_3_2',
        'jacket_3_3', 'jacket_3_4', 'jacket_3_5', 'jacket_4_1', 'jacket_4_2', 'jacket_4_3',
        'jacket_4_4', 'jacket_4_5', 'jacket_5_1', 'jacket_5_2', 'jacket_5_3', 'jacket_5_4',
        'jacket_5_5', 'jacket_6_1', 'jacket_6_2', 'jacket_6_3', 'jacket_6_4', 'jacket_6_5',
        'pelvis', 'thigh_l', 'calf_l', 'ankle_l', 'toe_l', 'thigh_r',
        'calf_r', 'ankle_r', 'toe_r',
    ))),
    ('nosine', _bone_map((
        'root', 'hip', 'spine_1', 'spine_2', 'neck', 'head',
        'jaw', 'tongue_1', 'tongue_2', 'lip_lower_c', 'lip_lower_r', 'lip_lower_l',
        'eyelid_lower_l', 'eyebrow_3_l', 'eyebrow_2_l', 'eyebrow_1_l', 'eyebrow_1_r', 'eyebrow_2_r',
        'eyebrow_3_r', 'eye_l', 'eyelid_upper_l', 'eye_r', 'eyelid_upper_r', 'eyelid_lower_r',
        'nose', 'lip_upper_r', 'lip_corner_r', 'lip_upper_c', 'lip_upper_l', 'lip_corner_l',
        'hair_1', 'hair_2', 'cheek_l', 'cheek_r', 'breast_l', 'breast_end_l',
        'breast_r', 'breast_end_r', 'shoulder_l', 'bicep_l', 'elbow_l', 'wrist_l',
        'index1_l', 'index2_l', 'index3_l', 'middle1_l', 'middle2_l', 'middle3_l',
        'ring1_l', 'ring2_l', 'ring3_l', 'pinky1_l', 'pinky2_l', 'pinky3_l',
        'thumb1_l', 'thumb2_l', 'weapon_l', 'wrist_fix_l', 'bicep_fix_l', 'shoulder_r',
        'bicep_r', 'elbow_r', 'wrist_r', 'index1_r', 'index2_r', 'index3_r',
        'middle1_r', 'middle2_r', 'middle3_r', 'ring1_r', 'ring2_r', 'ring3_r',
        'pinky1_r', 'pinky2_r', 'pinky3_r', 'thumb1_r', 'thumb2_r', 'weapon_r',
        'wrist_fix_r', 'bicep_fix_r', 'pelvis', 'thigh_l', 'calf_l', 'ankle_l',
        'toe_l', 'thigh_r', 'calf_r', 'ankle_r', 'toe_r',
    ))),
    ('alister/winston', _bone_map((
        'root', 'hip', 'pelvis', 'thigh_l', 'calf_l', 'ankle_l',
        'toe_l', 'thigh_r', 'calf_r', 'ankle_r', 'toe_r', 'spine_1',
        'spine_2', 'spine_3', 'neck', 'head', 'jaw', 'tongue_1',
        'tongue_2', 'lip_lower_l', 'lip_lower_c', 'lip_lower_r', 'eyelid_lower_l', 'eye_l',
        'eyelid_upper_l', 'eyebrow_1_r', 'eyebrow_2_r', 'eyebrow_3_r', 'eyelid_upper_r', 'eye_r',
        'eyelid_lower_r', 'nose', 'eyebrow_1_l', 'eyebrow_2_l', 'eyebrow_3_l', 'lip_corner_r',
        'lip_upper_r', 'lip_upper_c', 'lip_upper_l', 'lip_corner_l', 'shoulder_l', 'bicep_l',
        'elbow_l', 'wrist_l', 'index1_l', 'index2_l', 'index3_l', 'ring1_l',
        'ring2_l', 'ring3_l', 'middle1_l', 'middle2_l', 'middle3_l', 'pinky1_l',
        'pinky2_l', 'pinky3_l', 'thumb1_l', 'thumb2_l', 'shoulder_r', 'bicep_r',
        'elbow_r', 'wrist_r', 'index1_r', 'index2_r', 'index3_r', 'ring1_r',
        'ring2_r', 'ring3_r', 'middle1_r', 'middle2_r', 'middle3_r', 'pinky1_r',
        'pinky2_r', 'pinky3_r', 'thumb1_r', 'thumb2_r',
    ))),
    ('zip', _bone_map((
        'root', 'hip', 'spine_1', 'spine_2', 'spine_3', 'neck',
        'head', 'jaw', 'lip_lower_c', 'tongue_1', 'tongue_2', 'lip_lower_l',
        'lip_lower_r', 'eyelid_lower_l', 'eyebrow_3_l', 'eyebrow_2_l', 'eyebrow_1_l', 'eye_l',
        'eyelid_upper_l', 'nose', 'lip_upper_c', 'lip_upper_l', 'lip_corner_l', 'eyebrow_1_r',
        'eyebrow_2_r', 'eyebrow_3_r', 'eyelid_upper_r', 'eye_r', 'eyelid_lower_r', 'lip_upper_r',
        'lip_corner_r', 'shoulder_l', 'bicep_l', 'elbow_l', 'wrist_l', 'index1_l',
        'index2_l', 'index3_l', 'middle1_l', 'middle2_l', 'middle3_l', 'thumb1_l',
        'thumb2_l', 'ring1_l', 'ring2_l', 'ring3_l', 'pinky1_l', 'pinky2_l',
        'pinky3_l', 'hand_tracking_l', 'shoulder_r', 'bicep_r', 'elbow_r', 'wrist_r',
        'index1_r', 'index2_r', 'index3_r', 'middle1_r', 'middle2_r', 'middle3_r',
        'thumb1_r', 'thumb2_r', 'ring1_r', 'ring2_r', 'ring3_r', 'pinky1_r',
        'pinky2_r', 'pinky3_r', 'hand_tracking_r', 'pelvis', 'thigh_l', 'calf_l',
        'ankle_l', 'toe_l', 'thigh_r', 'calf_r', 'ankle_r', 'toe_r',
    ))),
    ('rutland', _bone_map((
        'root', 'hip', 'pelvis', 'thigh_l', 'calf_l', 'ankle_l',
        'toe_l', 'thigh_r', 'calf_r', 'ankle_r', 'toe_r', 'spine_1',
        'spine_2', 'spine_3', 'neck', 'head', 'jaw', 'tongue_1',
        'tongue_2', 'lip_lower_l', 'lip_lower_c', 'lip_lower_r', 'eyelid_lower_l', 'eye_l',
        'eyelid_upper_l', 'eyebrow_1_r', 'eyebrow_2_r', 'eyebrow_3_r', 'eyelid_upper_r', 'eye_r',
        'eyelid_lower_r', 'nose', 'eyebrow_1_l', 'eyebrow_2_l', 'eyebrow_3_l', 'lip_corner_r',
        'lip_upper_r', 'lip_upper_c', 'lip_upper_l', 'lip_corner_l', 'shoulder_r', 'bicep_r',
        'elbow_r', 'wrist_r', 'index1_r', 'index2_r', 'index3_r', 'ring1_r',
        'ring2_r', 'ring3_r', 'middle1_r', 'middle2_r', 'middle3_r', 'pinky1_r',
        'pinky2_r', 'pinky3_r', 'thumb1_r', 'thumb2_r', 'shoulder_l', 'bicep_l',
        'elbow_l', 'wrist_l', 'index1_l', 'index2_l', 'index3_l', 'ring1_l',
        'ring2_l', 'ring3_l', 'middle1_l', 'middle2_l', 'middle3_l', 'pinky1_l',
        'pinky2_l', 'pinky3_l', 'thumb1_l', 'thumb2_l',
    ))),
    ('laras_mom', _bone_map((
        'root', 'hip', 'spine_1', 'spine_2', 'neck', 'head',
        'jaw', 'tongue_1', 'tongue_2', 'lip_lower_c', 'lip_lower_r', 'lip_lower_l',
        'eyelid_lower_l', 'eyebrow_3_l', 'eyebrow_2_l', 'eyebrow_1_l', 'eyebrow_1_r', 'eyebrow_2_r',
        'eyebrow_3_r', 'eye_l', 'eyelid_upper_l', 'eye_r', 'eyelid_upper_r', 'eyelid_lower_r',
        'nose', 'lip_upper_r', 'lip_corner_r', 'lip_upper_c', 'lip_upper_c_2', 'lip_upper_l',
        'lip_corner_l', 'cheek_l', 'cheek_r', 'hair_fringe', 'breast_l', 'breast_r',
        'shoulder_l', 'bicep_l', 'elbow_l', 'wrist_l', 'index1_l', 'index2_l',
        'index3_l', 'middle1_l', 'middle2_l', 'middle3_l', 'ring1_l', 'ring2_l',
        'ring3_l', 'pinky1_l', 'pinky2_l', 'pinky3_l', 'thumb1_l', 'thumb2_l',
        'wrist_fix_l', 'bicep_fix_l', 'shoulder_l', 'bicep_l', 'elbow_l', 'wrist_l',
        'index1_l', 'index2_l', 'index3_l', 'middle1_l', 'middle2_l', 'middle3_l',
        'ring1_l', 'ring2_l', 'ring3_l', 'pinky1_l', 'pinky2_l', 'pinky3_l',
        'thumb1_l', 'thumb2_l', 'wrist_fix_l', 'bicep_fix_l', 'pelvis', 'thigh_l',
        'calf_l', 'ankle_l', 'toe_l', 'thigh_r', 'calf_r', 'ankle_r',
        'toe_r',
    ))),
    ('amanda', _bone_map((
        'root', 'hip', 'spine_1', 'spine_2', 'neck', 'head',
        'jaw', 'tongue_1', 'tongue_2', 'lip_lower_c', 'lip_lower_r', 'lip_lower_l',
        'eyelid_lower_l', 'eyebrow_3_l', 'eyebrow_2_l', 'eyebrow_1_l', 'eyebrow_1_r', 'eyebrow_2_r',
        'eyebrow_3_r', 'eye_l', 'eyelid_upper_l', 'eye_r', 'eyelid_upper_r', 'eyelid_lower_r',
        'nose', 'lip_upper_r', 'lip_corner_r', 'lip_upper_c', 'lip_upper_l', 'lip_corner_l',
        'hair_1', 'hair_2', 'breast_l', 'breast_end_l', 'breast_r', 'breast_end_r',
        'shoulder_l', 'bicep_l', 'elbow_l', 'wrist_l', 'index1_l', 'index2_l',
        'index3_l', 'middle1_l', 'middle2_l', 'middle3_l', 'ring1_l', 'ring2_l',
        'ring3_l', 'pinky1_l', 'pinky2_l', 'pinky3_l', 'thumb1_l', 'thumb2_l',
        'weapon_l', 'wrist_fix_l', 'bicep_fix_l', 'shoulder_r', 'bicep_r', 'elbow_r',
        'wrist_r', 'index1_r', 'index2_r', 'index3_r', 'middle1_r', 'middle2_r',
        'middle3_r', 'ring1_r', 'ring2_r', 'ring3_r', 'pinky1_r', 'pinky2_r',
        'pinky3_r', 'thumb1_r', 'thumb2_r', 'weapon_r', 'wrist_fix_r', 'bicep_fix_r',
        'pelvis', 'thigh_l', 'calf_l', 'ankle_l', 'toe_l', 'thigh_r',
        'calf_r', 'ankle_r', 'toe_r',
    ))),
    ('tamori', _bone_map((
        'root', 'hip', 'spine_1', 'spine_2', 'spine_3', 'neck',
        'head', 'jaw', 'lip_lower_c', 'tongue_1', 'tongue_2', 'lip_lower_l',
        'lip_lower_r', 'eyelid_lower_l', 'eyebrow_3_l', 'eyebrow_2_l', 'eyebrow_1_l', 'eye_l',
        'eyelid_upper_l', 'nose', 'lip_upper_c', 'lip_upper_l', 'lip_corner_l', 'eyebrow_1_r',
        'eyebrow_2_r', 'eyebrow_3_r', 'eyelid_upper_r', 'eye_r', 'eyelid_lower_r', 'lip_upper_r',
        'lip_corner_r', 'shoulder_r', 'bicep_r', 'elbow_r', 'wrist_r', 'index1_r',
        'index2_r', 'index3_r', 'middle1_r', 'middle2_r', 'middle3_r', 'thumb1_r',
        'thumb2_r', 'ring1_r', 'ring2_r', 'ring3_r', 'pinky1_r', 'pinky2_r',
        'pinky3_r', 'hand_tracking_r', 'shoulder_l', 'bicep_l', 'elbow_l', 'wrist_l',
        'index1_l', 'index2_l', 'index3_l', 'middle1_l', 'middle2_l', 'middle3_l',
        'thumb1_l', 'thumb2_l', 'ring1_l', 'ring2_l', 'ring3_l', 'pinky1_l',
        'pinky2_l', 'pinky3_l', 'hand_tracking_l', 'pelvis', 'thigh_l', 'calf_l',
        'ankle_l', 'toe_l', 'thigh_r', 'calf_r', 'ankle_r', 'toe_r',
    ))),
])


def get_scheme_items():
    return tuple((name, name, f'Rename bones using the {name} naming scheme') for name in NAMING_SCHEMES.keys())


def get_scheme_map(name: str):
    return NAMING_SCHEMES.get(name)
